parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''

doctrine:
  dbal:
    # configure these for your database server
    driver: 'pdo_mysql'
    server_version: '8.0'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

    url: '%env(resolve:DATABASE_URL)%'

    types:
      aggregateId:
        class: "Common\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\AggregateIdType"
      aggregateId_AutoIncrement:
        class: "Common\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\AggregateIdAIType"
      aggregateIdString:
        class: "Common\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\AggregateIdStringType"
      matrikelnummer:
        class: "Studi\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\MatrikelnummerType"
      studiHash:
        class: "Studi\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\StudiHashType"
      loginHash:
        class: "Studi\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\LoginHashType"
      wertung:
        class: "Wertung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\WertungType"
      itemWertungsId:
        class: "Wertung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\ItemWertungsIdType"
      clusterId:
        class: "Cluster\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\ClusterIdType"
      clusterCode:
        class: "Cluster\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\ClusterCodeType"
      itemSchwierigkeit:
        class: "Pruefung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\ItemSchwierigkeitType"
      pruefungsId:
        class: "Pruefung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\PruefungsIdType"
      pruefungsItemId:
        class: "Pruefung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\PruefungsItemIdType"
      pruefungsPeriode:
        class: "Pruefung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\PruefungsPeriodeType"
      studiPruefungsId:
        class: "StudiPruefung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\StudiPruefungsIdType"
      antwortCode:
        class: "Pruefung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\AntwortCodeType"
      selbstBewertungsId:
        class: "EPA\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\SelbstBewertungsIdType"
      fremdBewertungsId:
        class: "EPA\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\FremdBewertungsIdType"
      fremdBewertungsAnfrageId:
        class: "EPA\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\FremdBewertungsAnfrageIdType"
      fremdBewertungsAnfrageTaetigkeiten:
        class: "EPA\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\FremdBewertungsAnfrageTaetigkeitenType"
      fremdBewertungsAnfrageKommentar:
        class: "EPA\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\FremdBewertungsAnfrageKommentarType"
      fremdBewertungsBewertungen:
        class: "EPA\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\FremdBewertungsBewertungenType"
      lernzielNummer:
        class: "DatenImport\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\LernzielNummerType"

    mapping_types:
      aggregateId: integer
      aggregateId_AutoIncrement: integer
      aggregateString: string
      matrikelnummer: integer
      studiHash: string
      loginHash: string
      wertung: integer
      itemWertungsId: integer
      clusterId: integer
      clusterCode: string
      itemSchwierigkeit: integer
      pruefungsId: string
      pruefungsItemId: string
      pruefungsPeriode: integer
      studiPruefungsId: integer
      antwortCode: string
      selbstBewertungsId: integer
      fremdBewertungsId: integer
      fremdBewertungsAnfrageId: integer
      fremdBewertungsAnfrageTaetigkeiten: string
      fremdBewertungsAnfrageKommentar: string
      fremdBewertungsBewertungen: string
      lernzielNummer: integer

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    #        naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

    mappings:

      CommmonMapping:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Common/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "Common\\Domain"
      CommmonUserMapping:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Common/Infrastructure/Persistence/DB/Resources/Mapping/User"
        prefix:               "Common\\Domain\\User"

      AbstractEvent:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Common/Infrastructure/Persistence/DB/Resources/MappingApplication/AbstractEvent"
        prefix:               "Common\\Application\\AbstractEvent"

      Cluster:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Cluster/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "Cluster\\Domain"

      EPA:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/EPA/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "EPA\\Domain"

      EPASelbstBEwertung:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/EPA/Infrastructure/Persistence/DB/Resources/Mapping/SelbstBewertung"
        prefix:               "EPA\\Domain\\SelbstBewertung"

      EPAFremdBEwertung:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/EPA/Infrastructure/Persistence/DB/Resources/Mapping/FremdBewertung"
        prefix:               "EPA\\Domain\\FremdBewertung"

      Pruefung:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Pruefung/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "Pruefung\\Domain"

      Pruefung_FrageAntwort:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Pruefung/Infrastructure/Persistence/DB/Resources/Mapping/FrageAntwort"
        prefix:               "Pruefung\\Domain\\FrageAntwort"

      Studi:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Studi/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "Studi\\Domain"

      StudiPruefung:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/StudiPruefung/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "StudiPruefung\\Domain"

      Studienfortschritt:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Studienfortschritt/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "Studienfortschritt\\Domain"

      Wertung:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/Wertung/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "Wertung\\Domain"

      DatenImport:
        is_bundle:            false
        mapping:              true
        type:                 yml
        dir:                  "%kernel.project_dir%/src/DatenImport/Infrastructure/Persistence/DB/Resources/Mapping"
        prefix:               "DatenImport\\Domain"