parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            aggregateId:
                class: "Common\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\AggregateIdType"
            aggregateIdString:
                class: "Common\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\AggregateIdStringType"
            studiHash:
                class: "Studi\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\StudiHashType"
            wertung:
                class: "Wertung\\Infrastructure\\Persistence\\DB\\DoctrineTypes\\WertungType"
        mapping_types:
            aggregateId: integer
            aggregateString: string
            studiHash: string
            wertung: integer

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        mappings:
            CommmonMapping:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/Common/Infrastructure/Persistence/DB/Resources/Mapping"
                prefix:               "Common\\Domain"

            AbstractEvent:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/Common/Infrastructure/Persistence/DB/Resources/MappingApplication/AbstractEvent"
                prefix:               "Common\\Application\\AbstractEvent"

            Cluster:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/Cluster/Infrastructure/Persistence/DB/Resources/Mapping"
                prefix:               "Cluster\\Domain"

            Pruefung:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/Pruefung/Infrastructure/Persistence/DB/Resources/Mapping"
                prefix:               "Pruefung\\Domain"

            Studi:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/Studi/Infrastructure/Persistence/DB/Resources/Mapping"
                prefix:               "Studi\\Domain"

            StudiPruefung:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/StudiPruefung/Infrastructure/Persistence/DB/Resources/Mapping"
                prefix:               "StudiPruefung\\Domain"

            Wertung:
                is_bundle:            false
                mapping:              true
                type:                 yml
                dir:                  "%kernel.project_dir%/src/Wertung/Infrastructure/Persistence/DB/Resources/Mapping"
                prefix:               "Wertung\\Domain"