parameters:
    # Adds a fallback if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(LDAP_HOST): 'info.charite.de'
    env(LDAP_PORT): '636'
    env(LDAP_BASE_DN): 'dc=charite.de'
    env(LDAP_BIND_DN): 'uid=%,cn=personen,dc=charite.de'

