SSOController:
  type: annotation
  resource: "../../src/SSO/Infrastructure"

StudienfortschrittController:
  type: annotation
  resource: "../../src/Studienfortschritt/Infrastructure"

StudiPruefungController:
    type: annotation
    resource: "../../src/StudiPruefung/Infrastructure"

EPAController:
  type: annotation
  resource: "../../src/EPA/Infrastructure"



#    type: annotation


#controllers:
#    resource1: "../../src/Cluster/"
#        type: annotation
#    resource2: "../../src/Pruefung/"
#        type: annotation
#    resource3: "../../src/Studi/"
#        type: annotation
#    resource4: "../../src/StudiPruefung/"
#        type: annotation
#    resource5: "../../src/Wertung/"
#        type: annotation