Common\Application\AbstractEvent\StoredEvent:
  type: entity
  table: event

  id:
    id:
      type: aggregateId

  fields:
    occurredOn:
      type: datetime_immutable
      nullable: false
    byUserId:
      type: integer
      nullable: true

  embedded:
    eventClass:
      class: StoredEventClass
      columnPrefix: false
    eventBody:
      class: StoredEventBody
      columnPrefix: false

  indexes:
    occurredOn:
      columns: occurredOn
    byUserId:
      columns: byUserId
    eventClass:
      columns: class