version: "3"
services:
  web:
    image: nginx:alpine
    restart: always
    depends_on:
      - app
    ports:
        - "8080:80"
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf:ro
      - webroot_data:/var/www/levelup/public:ro

  app:
    image: pawelka/levelup-backend
    build:
      context: ../
      dockerfile: docker_config/app.dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - webroot_data:/shared/app-webroot
      - ../src:/var/www/levelup/src
    environment:
      DATABASE_URL: mysql://${LEVELUP_USER}:${LEVELUP_PASSWORD}@db:3306/${COMPOSE_PROJECT_NAME}
      APP_SECRET: $APP_KEY
      APP_ENV: 'prod'
      APP_DEBUG: 'false'
      MAILER_URL: ''
      SSO_OPENID_CLIENT_ID: foo
      SSO_OPENID_CLIENT_SECRET: bar
      SSO_OPENID_REDIRECT_URL: http://localhost:8080/ssoSuccess
      SSO_OPENID_PROVIDER_URL: http://sso:9000
      SSO_OPENID_TOKEN_ENDPOINT: http://sso:9000/token
      SSO_OPENID_USERINFO_ENDPOINT: http://sso:9000/me
      SSO_OPENID_END_SESSION_ENDPOINT: http://sso:9000/session/end
      SSO_OPENID_AUTHORIZATION_ENDPOINT: http://localhost:8081/auth
      LDAP_HOST: ldap
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=levelup,dc=de
      LDAP_BIND_DN: cn=%,dc=levelup,dc=de

  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $COMPOSE_PROJECT_NAME
      MYSQL_USER: $LEVELUP_USER
      MYSQL_PASSWORD: $LEVELUP_PASSWORD
      MYSQL_ROOT_PASSWORD: $LEVELUP_PASSWORD

  sso:
    image: qlik/simple-oidc-provider
    ports:
      - "8081:9000"
    volumes:
      - ./sso_config.json:/sso_config.json
      - ./sso_users.json:/sso_users.json
    environment:
      REDIRECTS: http://localhost:8080/ssoSuccess
      CONFIG_FILE: /sso_config.json
      USERS_FILE: /sso_users.json

  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: LevelUp
      LDAP_DOMAIN: levelup.de
      LDAP_ADMIN_PASSWORD: secret
      LDAP_TLS: "false"
    command: --copy-service
    volumes:
      - ./ldap_users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/00_users.ldif:ro
      - ./ldap_config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/02-security.ldif:ro
      - ./ldap_student.schema:/container/service/slapd/assets/config/bootstrap/schema/student.schema:ro

volumes:
  db_data:
  webroot_data:
