version: "3"
services:
  web:
    image: nginx:alpine
    restart: always
    depends_on:
      - app
    ports:
        - "8080:80"
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf:ro
      - webroot_data:/var/www/levelup/public:ro

  app:
    build:
      context: ../
      dockerfile: docker_config/app.dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - webroot_data:/shared/app-webroot
      - ../src:/var/www/levelup/src
    environment:
      DATABASE_URL: mysql://${LEVELUP_USER}:${LEVELUP_PASSWORD}@db:3306/${COMPOSE_PROJECT_NAME}
      APP_SECRET: $APP_KEY
      APP_ENV: 'prod'
      APP_DEBUG: 'false'
      MAILER_URL: ''

  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $COMPOSE_PROJECT_NAME
      MYSQL_USER: $LEVELUP_USER
      MYSQL_PASSWORD: $LEVELUP_PASSWORD
      MYSQL_ROOT_PASSWORD: $LEVELUP_PASSWORD

volumes:
  db_data:
  webroot_data:
