<?php

namespace Demo\Infrastructure\Persistence;

class MeilensteineJsonDemoData extends AbstractJsonDemoData
{
    protected $jsonData = [
        "meilensteine" => [
            [
                "code"             => 10,
                "kuerzel"          => "hausarb_best",
                "beschreibung"     => "Hausarbeit",
                "fachsemester"     => 6,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 20,
                "kuerzel"          => "erste_hilfe",
                "beschreibung"     => "Erste Hilfe",
                "fachsemester"     => 3,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 30,
                "kuerzel"          => "pflege_prakt",
                "beschreibung"     => "Pflegepraktikum",
                "fachsemester"     => 3,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 40,
                "kuerzel"          => "fam_reife",
                "beschreibung"     => "Famulatur-Reife",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 50,
                "kuerzel"          => "m1_eq",
                "beschreibung"     => "M1-Äquivalenz",
                "fachsemester"     => 6,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 60,
                "kuerzel"          => "m2_vor",
                "beschreibung"     => "M2-Voraussetzung",
                "fachsemester"     => 10,
                "erfuellt"         => FALSE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 70,
                "kuerzel"          => "stat_prfg",
                "beschreibung"     => "Stationenprüfung bestanden",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 101,
                "kuerzel"          => "anw_sem1",
                "beschreibung"     => "Anwesenheit Sem. 1",
                "fachsemester"     => 1,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 102,
                "kuerzel"          => "anw_sem2",
                "beschreibung"     => "Anwesenheit Sem. 2",
                "fachsemester"     => 2,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 103,
                "kuerzel"          => "anw_sem3",
                "beschreibung"     => "Anwesenheit Sem. 3",
                "fachsemester"     => 3,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 104,
                "kuerzel"          => "anw_sem4",
                "beschreibung"     => "Anwesenheit Sem. 4",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 105,
                "kuerzel"          => "anw_sem5",
                "beschreibung"     => "Anwesenheit Sem. 5",
                "fachsemester"     => 5,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 106,
                "kuerzel"          => "anw_sem6",
                "beschreibung"     => "Anwesenheit Sem. 6",
                "fachsemester"     => 6,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 107,
                "kuerzel"          => "anw_sem7",
                "beschreibung"     => "Anwesenheit Sem. 7",
                "fachsemester"     => 7,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 108,
                "kuerzel"          => "anw_sem8",
                "beschreibung"     => "Anwesenheit Sem. 8",
                "fachsemester"     => 8,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 109,
                "kuerzel"          => "anw_sem9",
                "beschreibung"     => "Anwesenheit Sem. 9",
                "fachsemester"     => 9,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 201,
                "kuerzel"          => "best_sem1",
                "beschreibung"     => "Abgeschlossen Sem. 1",
                "fachsemester"     => 1,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 202,
                "kuerzel"          => "best_sem2",
                "beschreibung"     => "Abgeschlossen Sem. 2",
                "fachsemester"     => 2,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 203,
                "kuerzel"          => "best_sem3",
                "beschreibung"     => "Abgeschlossen Sem. 3",
                "fachsemester"     => 3,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 204,
                "kuerzel"          => "best_sem4",
                "beschreibung"     => "Abgeschlossen Sem. 4",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 205,
                "kuerzel"          => "best_sem5",
                "beschreibung"     => "Abgeschlossen Sem. 5",
                "fachsemester"     => 5,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 206,
                "kuerzel"          => "best_sem6",
                "beschreibung"     => "Abgeschlossen Sem. 6",
                "fachsemester"     => 6,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 207,
                "kuerzel"          => "best_sem7",
                "beschreibung"     => "Abgeschlossen Sem. 7",
                "fachsemester"     => 7,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 208,
                "kuerzel"          => "best_sem8",
                "beschreibung"     => "Abgeschlossen Sem. 8",
                "fachsemester"     => 8,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 209,
                "kuerzel"          => "best_sem9",
                "beschreibung"     => "Abgeschlossen Sem. 9",
                "fachsemester"     => 9,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 210,
                "kuerzel"          => "best_sem10",
                "beschreibung"     => "Abgeschlossen Sem. 10",
                "fachsemester"     => 10,
                "erfuellt"         => FALSE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 304,
                "kuerzel"          => "voraus_sem4",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 4",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 305,
                "kuerzel"          => "voraus_sem5",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 5",
                "fachsemester"     => 5,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 306,
                "kuerzel"          => "voraus_sem6",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 6",
                "fachsemester"     => 6,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 307,
                "kuerzel"          => "voraus_sem7",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 7",
                "fachsemester"     => 7,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 308,
                "kuerzel"          => "voraus_sem8",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 8",
                "fachsemester"     => 8,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 309,
                "kuerzel"          => "voraus_sem9",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 9",
                "fachsemester"     => 9,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 310,
                "kuerzel"          => "voraus_sem10",
                "beschreibung"     => "Voraussetzung erfüllt Sem. 10",
                "fachsemester"     => 10,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => NULL,
            ],
            [
                "code"             => 401,
                "kuerzel"          => "MC-Sem1",
                "beschreibung"     => "MC-Prüfung Sem. 1",
                "fachsemester"     => 1,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 11353,
                "format"           => "mc",
            ],
            [
                "code"             => 402,
                "kuerzel"          => "MC-Sem2",
                "beschreibung"     => "MC-Prüfung Sem. 2",
                "fachsemester"     => 2,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 9889,
                "format"           => "mc",
            ],
            [
                "code"             => 403,
                "kuerzel"          => "MC-Sem3",
                "beschreibung"     => "MC-Prüfung Sem. 3",
                "fachsemester"     => 3,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => "mc",
            ],
            [
                "code"             => 404,
                "kuerzel"          => "MC-Sem4",
                "beschreibung"     => "MC-Prüfung Sem. 4",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 9078,
                "format"           => "mc",
            ],
            [
                "code"             => 405,
                "kuerzel"          => "MC-Sem5",
                "beschreibung"     => "MC-Prüfung Sem. 5",
                "fachsemester"     => 5,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 7759,
                "format"           => "mc",
            ],
            [
                "code"             => 406,
                "kuerzel"          => "MC-Sem6",
                "beschreibung"     => "MC-Prüfung Sem. 6",
                "fachsemester"     => 6,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 5620,
                "format"           => "mc",
            ],
            [
                "code"             => 407,
                "kuerzel"          => "MC-Sem7",
                "beschreibung"     => "MC-Prüfung Sem. 7",
                "fachsemester"     => 7,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 3478,
                "format"           => "mc",
            ],
            [
                "code"             => 408,
                "kuerzel"          => "MC-Sem8",
                "beschreibung"     => "MC-Prüfung Sem. 8",
                "fachsemester"     => 8,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 1992,
                "format"           => "mc",
            ],
            [
                "code"             => 409,
                "kuerzel"          => "MC-Sem9",
                "beschreibung"     => "MC-Prüfung Sem. 9",
                "fachsemester"     => 9,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 35818,
                "format"           => "mc",
            ],
            [
                "code"             => 501,
                "kuerzel"          => "stat_prfg_sem2_vorklinik",
                "beschreibung"     => "Mündliche Prüfung Sem. 2 (Vorklinik)",
                "fachsemester"     => 2,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => "station",
            ],
            [
                "code"             => 502,
                "kuerzel"          => "stat_prfg_sem2_klinik",
                "beschreibung"     => "Praktische Prüfung Sem. 2 (Klinik)",
                "fachsemester"     => 2,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => NULL,
                "format"           => "station",
            ],
            [
                "code"             => 503,
                "kuerzel"          => "stat_prfg_sem4_vorklinik",
                "beschreibung"     => "Mündliche Prüfung Sem. 4 (Vorklinik)",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 26076,
                "format"           => "station",
            ],
            [
                "code"             => 504,
                "kuerzel"          => "stat_prfg_sem4_klinik",
                "beschreibung"     => "Praktische Prüfung Sem. 4 (Klinik)",
                "fachsemester"     => 4,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 26155,
                "format"           => "station",
            ],
            [
                "code"             => 509,
                "kuerzel"          => "osce_sem9_klinik",
                "beschreibung"     => "OSCE-Prüfung Sem. 9",
                "fachsemester"     => 9,
                "erfuellt"         => TRUE,
                "studiPruefungsId" => 38030,
                "format"           => "station",
            ],
        ],
    ];

    public function isResponsibleFor(string $pathInfo): bool {
        return $pathInfo == "/api/meilensteine"
            || $pathInfo == "/api/studienfortschritt";
    }
}