# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: "../src/**/ServiceDefinition/*.yaml" }

parameters:
    app.file-based-repository-dir: '%kernel.project_dir%/var/data/fileBasedRepositoryData'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

#    router.default:
#        class: Symfony\Bundle\FrameworkBundle\Routing\Router
#        tags:
#            - { name: monolog.logger, channel: router }
#            - { name: container.service_subscriber, id: routing.loader }

    Common\Application\DomainEvent\DomainEventPublisher:
        # inject all services tagged with ddd.domainEventSubscriber as first argument
        class: Common\Infrastructure\Event\Services\SimpleDomainEventPublisher
        autowire: false
        arguments: [!tagged ddd.domainEventSubscriber,  '@Common\Domain\Services\CurrentUserIdService']

    Common\Application\Command\CommandBus:
        # inject all services tagged with ddd.domainEventSubscriber as first argument
        class: Common\Infrastructure\Event\Services\SimpleCommandBus
        public: true
        autowire: false
        arguments: [!tagged ddd.domainCommandHandler]
        calls:
            - [setDomainEventPublisher, ['@Common\Application\DomainEvent\DomainEventPublisher']]

    Common\Domain\Services\CurrentUserIdService:
        class: FBToolCommon\Infrastructure\UserInterface\Web\Service\CurrentWebUserIdService

    SSO\Domain\EingeloggterStudiService:
        class: SSO\Infrastructure\Web\Service\WebEingeloggterStudiService

    Common\Infrastructure\UserInterface\Web\Service\ChariteSSOService:
        arguments:
            - '%env(SSO_OPENID_CLIENT_ID)%'
            - '%env(SSO_OPENID_CLIENT_SECRET)%'
            - '%env(SSO_OPENID_REDIRECT_URL)%'
            - '%env(SSO_OPENID_PROVIDER_URL)%'
            - '%env(SSO_OPENID_TOKEN_ENDPOINT)%'
            - '%env(SSO_OPENID_USERINFO_ENDPOINT)%'
            - '%env(SSO_OPENID_END_SESSION_ENDPOINT)%'
            - '%env(SSO_OPENID_AUTHORIZATION_ENDPOINT)%'

    Common\Infrastructure\UserInterface\Web\Service\ChariteLDAPService:
        arguments:
            - '%env(LDAP_HOST)%'
            - '%env(LDAP_PORT)%'
            - '%env(LDAP_TLS)%'
            - '%env(LDAP_BASE_DN)%'
            - '%env(LDAP_BIND_DN)%'
