parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # false allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.


    Studi\Domain\Service\StudiHashCreator:
        class: Studi\Infrastructure\Service\StudiHashCreator_SHA256
        arguments:
            - '%env(APP_SECRET)%'

    Studi\Domain\Service\LoginHashCreator:
        class: Studi\Infrastructure\Service\LoginHashCreator_SHA256
        arguments:
            - '%env(APP_SECRET)%'