parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # false allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    StudiPruefung-Domain-StudiPruefungsRepository-DoctrineRepo:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - StudiPruefung\Domain\StudiPruefung

    StudiPruefung\Domain\StudiPruefungsRepository:
        class: StudiPruefung\Infrastructure\Persistence\DB\DBStudiPruefungsRepository
        arguments:
          - "@StudiPruefung-Domain-StudiPruefungsRepository-DoctrineRepo"
          - "@doctrine.orm.entity_manager"
        public: true